/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AAffix: typeof import("@arco-design/web-vue")["Affix"];
    ABreadcrumb: typeof import("@arco-design/web-vue")["Breadcrumb"];
    ABreadcrumbItem: typeof import("@arco-design/web-vue")["BreadcrumbItem"];
    AButton: typeof import("@arco-design/web-vue")["Button"];
    ACard: typeof import("@arco-design/web-vue")["Card"];
    ACol: typeof import("@arco-design/web-vue")["Col"];
    AConfigProvider: typeof import("@arco-design/web-vue")["ConfigProvider"];
    ADivider: typeof import("@arco-design/web-vue")["Divider"];
    ADoption: typeof import("@arco-design/web-vue")["Doption"];
    ADrawer: typeof import("@arco-design/web-vue")["Drawer"];
    ADropdown: typeof import("@arco-design/web-vue")["Dropdown"];
    AForm: typeof import("@arco-design/web-vue")["Form"];
    AFormItem: typeof import("@arco-design/web-vue")["FormItem"];
    AInput: typeof import("@arco-design/web-vue")["Input"];
    AInputNumber: typeof import("@arco-design/web-vue")["InputNumber"];
    AInputPassword: typeof import("@arco-design/web-vue")["InputPassword"];
    ALayout: typeof import("@arco-design/web-vue")["Layout"];
    ALayoutContent: typeof import("@arco-design/web-vue")["LayoutContent"];
    ALayoutFooter: typeof import("@arco-design/web-vue")["LayoutFooter"];
    ALayoutSider: typeof import("@arco-design/web-vue")["LayoutSider"];
    AMenu: typeof import("@arco-design/web-vue")["Menu"];
    AMenuItem: typeof import("@arco-design/web-vue")["MenuItem"];
    AModal: typeof import("@arco-design/web-vue")["Modal"];
    AOption: typeof import("@arco-design/web-vue")["Option"];
    AResult: typeof import("@arco-design/web-vue")["Result"];
    ASelect: typeof import("@arco-design/web-vue")["Select"];
    ASpace: typeof import("@arco-design/web-vue")["Space"];
    ASubMenu: typeof import("@arco-design/web-vue")["SubMenu"];
    ASwitch: typeof import("@arco-design/web-vue")["Switch"];
    ATable: typeof import("@arco-design/web-vue")["Table"];
    ATableColumn: typeof import("@arco-design/web-vue")["TableColumn"];
    ATooltip: typeof import("@arco-design/web-vue")["Tooltip"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
