/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Block: typeof import('./../src/components/global-setting/block.vue')['default']
    Breadcrumb: typeof import('./../src/components/breadcrumb/index.vue')['default']
    Chart: typeof import('./../src/components/chart/index.vue')['default']
    Footer: typeof import('./../src/components/footer/index.vue')['default']
    FormWrapper: typeof import('./../src/components/global-setting/form-wrapper.vue')['default']
    GlobalSetting: typeof import('./../src/components/global-setting/index.vue')['default']
    Menu: typeof import('./../src/components/menu/index.vue')['default']
    MqAdvanceQuery: typeof import('./../src/components/mqAdvanceQuery/index.vue')['default']
    MqContainer: typeof import('./../src/components/mqContainer/index.vue')['default']
    MqModal: typeof import('./../src/components/mqModal/index.vue')['default']
    MqSelect: typeof import('./../src/components/mqSelect/index.vue')['default']
    MqTable: typeof import('./../src/components/mqTable/index.vue')['default']
    Nav: typeof import('./../src/components/nav/index.vue')['default']
    Navbar: typeof import('./../src/components/navbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./../src/components/tab-bar/index.vue')['default']
    TabItem: typeof import('./../src/components/tab-bar/tab-item.vue')['default']
    TsxDom: typeof import('./../src/components/tsxDom/index.vue')['default']
  }
}
